# Generated by Django 4.0.6 on 2022-08-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companyjobpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.TextField(max_length=120)),
                ('description', models.TextField(max_length=120)),
                ('Requrirement', models.TextField(max_length=120)),
                ('Requirementdetails', models.TextField(max_length=120)),
                ('Creditcheck', models.TextField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='companyRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('number', models.IntegerField()),
                ('adderss', models.TextField(max_length=120)),
                ('password', models.CharField(max_length=120)),
                ('Gender', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
