# Generated by Django 4.0.6 on 2022-08-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyregistration',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='male', max_length=120),
        ),
    ]
