# Generated by Django 4.0.6 on 2022-08-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0002_alter_companyregistration_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyregistration',
            name='number',
            field=models.TextField(max_length=120),
        ),
    ]
