# Generated by Django 4.0.6 on 2022-08-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminEventAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.TextField(max_length=120)),
                ('TrainerName', models.TextField(max_length=120)),
                ('Requirment', models.TextField(max_length=120)),
                ('messeage', models.TextField(max_length=120)),
                ('EventDate', models.DateField()),
                ('Location', models.TextField(max_length=120)),
            ],
        ),
    ]
