# Generated by Django 4.0.6 on 2022-08-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Boss', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admineventadd',
            name='Status',
            field=models.TextField(default='Open', max_length=12),
        ),
    ]
