# Generated by Django 4.0.6 on 2022-08-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='male', max_length=120),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='number',
            field=models.TextField(max_length=120),
        ),
    ]
