# Generated by Django 4.0.6 on 2022-08-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerAddDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(max_length=120)),
                ('TrainerName', models.TextField(max_length=120)),
                ('TrainerDetails', models.TextField(max_length=120)),
                ('Requirement', models.TextField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='TrainerCredits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField(max_length=120)),
                ('TrainerName', models.TextField(max_length=120)),
                ('TrainerDetails', models.TextField(max_length=120)),
                ('Requirement', models.TextField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='TrainerRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('number', models.IntegerField()),
                ('adderss', models.TextField(max_length=120)),
                ('password', models.CharField(max_length=120)),
                ('Gender', models.BooleanField(default=False)),
            ],
        ),
    ]
