# Generated by Django 4.0.6 on 2022-08-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traineradddetails',
            name='Date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='trainerregistration',
            name='Gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='male', max_length=120),
        ),
    ]
