# Generated by Django 4.0.6 on 2022-08-16 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_traineradddetails_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainercredits',
            name='Date',
            field=models.DateField(auto_now=True),
        ),
    ]
